"""
Proxy Browser Bridge

Generates browser proxy configuration artefacts so that Chrome, Firefox, and
other clients can route their traffic through the UniVex proxy in a single
click.

Deliverables:
  - PAC (Proxy Auto-Configuration) file for both HTTP and HTTPS
  - JSON configuration blobs compatible with Chrome's ``--proxy-server`` flag
    and Firefox's ``user.js`` / ``prefs.js`` format
  - Downloadable CA certificate bundle for browser trust-store import
  - ``BrowserBridge`` class with async generation methods

OWASP: A07:2021-Identification and Authentication Failures
MITRE: T1557 (Man-in-the-Middle)
"""

from __future__ import annotations

import logging
import os
import textwrap
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Defaults pulled from environment (same vars as ProxyInterceptor)
# ---------------------------------------------------------------------------

_DEFAULT_PROXY_HOST = os.getenv("PROXY_HOST", "127.0.0.1")
_DEFAULT_PROXY_PORT = int(os.getenv("PROXY_PORT", "8080"))


# ---------------------------------------------------------------------------
# BrowserBridge
# ---------------------------------------------------------------------------


class BrowserBridge:
    """
    Generates browser proxy configuration files and instructions.

    All methods are synchronous — the class holds no mutable state after
    construction.

    Args:
        proxy_host: Hostname / IP of the proxy.  Clients must be able to reach
                    this address.
        proxy_port: TCP port of the proxy.
        bypass_list: List of hostnames / CIDR ranges that should bypass the
                     proxy (always includes ``localhost`` and ``127.0.0.1``).
    """

    _DEFAULT_BYPASS = [
        "localhost",
        "127.0.0.1",
        "::1",
        "*.local",
        "169.254.0.0/16",
    ]

    def __init__(
        self,
        proxy_host: str = _DEFAULT_PROXY_HOST,
        proxy_port: int = _DEFAULT_PROXY_PORT,
        bypass_list: Optional[List[str]] = None,
    ) -> None:
        self.proxy_host = proxy_host
        self.proxy_port = proxy_port
        self.bypass_list: List[str] = list(bypass_list or []) + self._DEFAULT_BYPASS

    # ------------------------------------------------------------------
    # PAC file
    # ------------------------------------------------------------------

    def generate_pac(self) -> str:
        """
        Generate a PAC (Proxy Auto-Configuration) file.

        The generated PAC routes all HTTP and HTTPS traffic through the proxy
        while respecting the configured bypass list.

        Returns:
            JavaScript string conforming to the PAC specification.
        """
        bypass_conditions = " ||\n        ".join(
            f'shExpMatch(host, "{pattern}")'
            for pattern in self.bypass_list
        )

        pac = textwrap.dedent(
            f"""\
            // UniVex Proxy Auto-Configuration (PAC) file
            // Generated by BrowserBridge
            // Proxy: {self.proxy_host}:{self.proxy_port}

            function FindProxyForURL(url, host) {{
                // Bypass the proxy for direct-access hosts
                if (
                    {bypass_conditions}
                ) {{
                    return "DIRECT";
                }}

                // Bypass local (non-FQDN) hostnames
                if (isPlainHostName(host)) {{
                    return "DIRECT";
                }}

                // Bypass RFC-1918 private address ranges
                if (
                    isInNet(host, "10.0.0.0",     "255.0.0.0") ||
                    isInNet(host, "172.16.0.0",    "255.240.0.0") ||
                    isInNet(host, "192.168.0.0",   "255.255.0.0")
                ) {{
                    return "DIRECT";
                }}

                return "PROXY {self.proxy_host}:{self.proxy_port}";
            }}
            """
        )
        return pac

    # ------------------------------------------------------------------
    # Chrome configuration
    # ------------------------------------------------------------------

    def chrome_config(self) -> Dict[str, Any]:
        """
        Return a dict describing how to configure Google Chrome to use the proxy.

        The ``flags`` list contains CLI flags that can be passed directly to
        ``chromium`` or ``google-chrome``.

        Returns:
            Dict with ``proxy_server``, ``bypass_list``, ``flags``, and
            ``launch_command`` keys.
        """
        proxy_server = f"{self.proxy_host}:{self.proxy_port}"
        bypass = ",".join(self.bypass_list)
        flags = [
            f"--proxy-server=http={proxy_server};https={proxy_server}",
            f"--proxy-bypass-list={bypass}",
            "--ignore-certificate-errors",
            "--ignore-certificate-errors-spki-list",
            "--ignore-urlfetcher-cert-requests",
        ]
        return {
            "proxy_server": proxy_server,
            "bypass_list": bypass,
            "flags": flags,
            "launch_command": f"chromium {' '.join(flags)} --user-data-dir=/tmp/univex-chrome",
            "pac_url": f"http://{self.proxy_host}:{self.proxy_port}/proxy.pac",
        }

    # ------------------------------------------------------------------
    # Firefox configuration
    # ------------------------------------------------------------------

    def firefox_user_js(self) -> str:
        """
        Generate a Firefox ``user.js`` snippet that configures the proxy.

        The returned string can be appended to an existing ``user.js`` or
        written to a new Firefox profile.

        Returns:
            String containing ``user_pref(...)`` declarations.
        """
        bypass = ", ".join(self.bypass_list)
        lines = [
            "// UniVex Proxy configuration — paste into Firefox user.js",
            'user_pref("network.proxy.type", 1);',
            f'user_pref("network.proxy.http", "{self.proxy_host}");',
            f'user_pref("network.proxy.http_port", {self.proxy_port});',
            f'user_pref("network.proxy.ssl", "{self.proxy_host}");',
            f'user_pref("network.proxy.ssl_port", {self.proxy_port});',
            f'user_pref("network.proxy.no_proxies_on", "{bypass}");',
            'user_pref("security.ssl.enable_ocsp_stapling", false);',
            'user_pref("security.enterprise_roots.enabled", true);',
        ]
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Generic JSON config
    # ------------------------------------------------------------------

    def json_config(self) -> Dict[str, Any]:
        """
        Return a generic JSON proxy configuration suitable for tools, CI
        systems, and HTTP client libraries.

        Returns:
            Dict with ``http_proxy``, ``https_proxy``, ``no_proxy``,
            ``pac_url``, ``browser`` instructions, and environment variables.
        """
        proxy_url = f"http://{self.proxy_host}:{self.proxy_port}"
        no_proxy = ",".join(self.bypass_list)
        return {
            "http_proxy": proxy_url,
            "https_proxy": proxy_url,
            "no_proxy": no_proxy,
            "pac_url": f"{proxy_url}/proxy.pac",
            "environment_variables": {
                "HTTP_PROXY": proxy_url,
                "HTTPS_PROXY": proxy_url,
                "NO_PROXY": no_proxy,
            },
            "curl_flags": f"--proxy {proxy_url} --insecure",
            "python_requests": {
                "proxies": {"http": proxy_url, "https": proxy_url},
                "verify": False,
            },
            "browser": {
                "chrome": self.chrome_config(),
                "firefox_user_js": self.firefox_user_js(),
            },
            "ca_cert_download_url": f"{proxy_url}/api/proxy/ca-cert",
            "instructions": (
                "1. Download and import the CA certificate into your browser trust store.\n"
                "2. Configure your browser or tool to use the proxy settings above.\n"
                "3. For Chrome, use the launch command in browser.chrome.launch_command.\n"
                "4. For Firefox, paste browser.firefox_user_js into your profile's user.js."
            ),
        }

    # ------------------------------------------------------------------
    # CA certificate helper
    # ------------------------------------------------------------------

    @staticmethod
    def get_ca_cert_path() -> Optional[str]:
        """
        Return the path to the CA certificate PEM file if it exists.

        Checks environment variable ``PROXY_CA_CERT_PATH`` and falls back to
        the mitmproxy default location.
        """
        env_path = os.getenv("PROXY_CA_CERT_PATH")
        if env_path and os.path.isfile(env_path):
            return env_path

        # mitmproxy default
        default = os.path.expanduser("~/.mitmproxy/mitmproxy-ca-cert.pem")
        if os.path.isfile(default):
            return default

        return None

    @staticmethod
    def read_ca_cert() -> Optional[bytes]:
        """
        Read and return the CA certificate PEM bytes, or *None* if unavailable.
        """
        path = BrowserBridge.get_ca_cert_path()
        if path is None:
            return None
        try:
            with open(path, "rb") as f:
                return f.read()
        except OSError as exc:
            logger.warning("Could not read CA cert at %s: %s", path, exc)
            return None

    # ------------------------------------------------------------------
    # Bypass helpers
    # ------------------------------------------------------------------

    def add_bypass(self, pattern: str) -> None:
        """Add a hostname / glob pattern to the bypass list."""
        if pattern not in self.bypass_list:
            self.bypass_list.append(pattern)

    def remove_bypass(self, pattern: str) -> bool:
        """Remove a bypass pattern. Returns True if it was found and removed."""
        if pattern in self.bypass_list:
            self.bypass_list.remove(pattern)
            return True
        return False
