apiVersion: 1
contactPoints:
  - orgId: 1
    name: default-email
    receivers:
      - uid: default-email
        type: email
        settings:
          addresses: "${ALERT_EMAIL:-admin@example.com}"
          singleEmail: false
