#!/usr/bin/env bash
# generate-certs.sh — Generate CA, server, and client certificates for UniVex MCP servers
# Day 12: mTLS for MCP Tool Servers
#
# Usage: ./scripts/generate-certs.sh
# Output: certs/  (excluded from git via .gitignore)

set -euo pipefail

CERTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/certs"
CA_DIR="${CERTS_DIR}/ca"
SERVER_DIR="${CERTS_DIR}/server"
CLIENT_DIR="${CERTS_DIR}/client"

CA_DAYS=3650
CERT_DAYS=365
CA_KEY_SIZE=4096
CERT_KEY_SIZE=2048

MCP_SERVERS=(naabu curl nuclei metasploit ffuf sqlmap cracker nikto)

echo "==> Creating certificate directories..."
mkdir -p "${CA_DIR}" "${SERVER_DIR}" "${CLIENT_DIR}"

# ---------------------------------------------------------------------------
# CA (Certificate Authority)
# ---------------------------------------------------------------------------
echo "==> Generating CA private key (${CA_KEY_SIZE}-bit RSA)..."
openssl genrsa -out "${CA_DIR}/ca.key" ${CA_KEY_SIZE}
chmod 600 "${CA_DIR}/ca.key"

echo "==> Generating self-signed CA certificate (${CA_DAYS} days)..."
openssl req -new -x509 -days ${CA_DAYS} \
  -key "${CA_DIR}/ca.key" \
  -out "${CA_DIR}/ca.crt" \
  -subj "/C=US/O=UniVex/CN=UniVex-CA"

echo "CA certificate generated: ${CA_DIR}/ca.crt"

# ---------------------------------------------------------------------------
# Server and client certificates per MCP server
# ---------------------------------------------------------------------------
for SERVER in "${MCP_SERVERS[@]}"; do
  echo ""
  echo "==> Processing MCP server: ${SERVER}"

  SERVER_SUBDIR="${SERVER_DIR}/${SERVER}"
  CLIENT_SUBDIR="${CLIENT_DIR}/${SERVER}"
  mkdir -p "${SERVER_SUBDIR}" "${CLIENT_SUBDIR}"

  # --- Server certificate ---
  echo "    Generating server key (${CERT_KEY_SIZE}-bit RSA)..."
  openssl genrsa -out "${SERVER_SUBDIR}/server.key" ${CERT_KEY_SIZE}
  chmod 600 "${SERVER_SUBDIR}/server.key"

  echo "    Generating server CSR..."
  openssl req -new \
    -key "${SERVER_SUBDIR}/server.key" \
    -out "${SERVER_SUBDIR}/server.csr" \
    -subj "/C=US/O=UniVex/CN=${SERVER}-mcp-server"

  echo "    Signing server certificate with CA (${CERT_DAYS} days)..."
  openssl x509 -req -days ${CERT_DAYS} \
    -in "${SERVER_SUBDIR}/server.csr" \
    -CA "${CA_DIR}/ca.crt" \
    -CAkey "${CA_DIR}/ca.key" \
    -CAcreateserial \
    -out "${SERVER_SUBDIR}/server.crt" \
    -extensions v3_req

  rm -f "${SERVER_SUBDIR}/server.csr"
  echo "    Server cert: ${SERVER_SUBDIR}/server.crt"

  # --- Client certificate ---
  echo "    Generating client key (${CERT_KEY_SIZE}-bit RSA)..."
  openssl genrsa -out "${CLIENT_SUBDIR}/client.key" ${CERT_KEY_SIZE}
  chmod 600 "${CLIENT_SUBDIR}/client.key"

  echo "    Generating client CSR..."
  openssl req -new \
    -key "${CLIENT_SUBDIR}/client.key" \
    -out "${CLIENT_SUBDIR}/client.csr" \
    -subj "/C=US/O=UniVex/CN=${SERVER}-mcp-client"

  echo "    Signing client certificate with CA (${CERT_DAYS} days)..."
  openssl x509 -req -days ${CERT_DAYS} \
    -in "${CLIENT_SUBDIR}/client.csr" \
    -CA "${CA_DIR}/ca.crt" \
    -CAkey "${CA_DIR}/ca.key" \
    -CAcreateserial \
    -out "${CLIENT_SUBDIR}/client.crt"

  rm -f "${CLIENT_SUBDIR}/client.csr"
  echo "    Client cert: ${CLIENT_SUBDIR}/client.crt"
done

# ---------------------------------------------------------------------------
# .gitignore note
# ---------------------------------------------------------------------------
GITIGNORE="${CERTS_DIR}/.gitignore"
if [ ! -f "${GITIGNORE}" ]; then
  cat > "${GITIGNORE}" <<'EOF'
# Certificate files — DO NOT COMMIT TO VERSION CONTROL
# Generated by scripts/generate-certs.sh
*
!.gitignore
EOF
  echo ""
  echo "NOTE: Created ${GITIGNORE} to prevent committing private keys."
fi

echo ""
echo "==> Certificate generation complete."
echo "    CA cert:  ${CA_DIR}/ca.crt"
echo "    Servers:  ${SERVER_DIR}/<server>/server.crt"
echo "    Clients:  ${CLIENT_DIR}/<server>/client.crt"
