"""
Graph database operations module.
Handles Neo4j node creation, relationships, and data ingestion.
"""

from app.graph.nodes import (
    DomainNode,
    SubdomainNode,
    IPNode,
    PortNode,
    ServiceNode,
    BaseURLNode,
    EndpointNode,
    ParameterNode,
    TechnologyNode,
    HeaderNode,
    CertificateNode,
    DNSRecordNode,
    VulnerabilityNode,
    CVENode,
    MitreDataNode,
    CapecNode,
    ExploitNode,
    ADUserNode,
    ADGroupNode,
    ADComputerNode,
    ADOUNode,
    ADGPONode,
    ADDomainNode,
    ADTrustNode,
)
from app.graph.relationships import (
    create_relationship,
    link_domain_subdomain,
    link_subdomain_ip,
    link_ip_port,
    link_port_service,
    link_port_baseurl,
    link_baseurl_endpoint,
    link_endpoint_parameter,
    link_baseurl_technology,
    link_baseurl_header,
    link_baseurl_certificate,
    link_subdomain_dnsrecord,
    link_vulnerability_endpoint,
    link_vulnerability_parameter,
    link_ip_vulnerability,
    link_technology_cve,
    link_cve_mitre,
    link_mitre_capec,
    link_exploit_cve,
    link_exploit_ip,
)
from app.graph.ingestion import (
    ingest_domain_discovery,
    ingest_port_scan,
    ingest_http_probe,
    ingest_resource_enumeration,
    ingest_vulnerability_scan,
    ingest_mitre_data,
)

__all__ = [
    # Node types
    'DomainNode',
    'SubdomainNode',
    'IPNode',
    'PortNode',
    'ServiceNode',
    'BaseURLNode',
    'EndpointNode',
    'ParameterNode',
    'TechnologyNode',
    'HeaderNode',
    'CertificateNode',
    'DNSRecordNode',
    'VulnerabilityNode',
    'CVENode',
    'MitreDataNode',
    'CapecNode',
    'ExploitNode',
    # Active Directory node types (BloodHound engine)
    'ADUserNode',
    'ADGroupNode',
    'ADComputerNode',
    'ADOUNode',
    'ADGPONode',
    'ADDomainNode',
    'ADTrustNode',
    # Relationship handlers
    'create_relationship',
    'link_domain_subdomain',
    'link_subdomain_ip',
    'link_ip_port',
    'link_port_service',
    'link_port_baseurl',
    'link_baseurl_endpoint',
    'link_endpoint_parameter',
    'link_baseurl_technology',
    'link_baseurl_header',
    'link_baseurl_certificate',
    'link_subdomain_dnsrecord',
    'link_vulnerability_endpoint',
    'link_vulnerability_parameter',
    'link_ip_vulnerability',
    'link_technology_cve',
    'link_cve_mitre',
    'link_mitre_capec',
    'link_exploit_cve',
    'link_exploit_ip',
    # Ingestion functions
    'ingest_domain_discovery',
    'ingest_port_scan',
    'ingest_http_probe',
    'ingest_resource_enumeration',
    'ingest_vulnerability_scan',
    'ingest_mitre_data',
]
